export const styles = {
  fixedBox: {
    position: 'fixed',
    top: 80,
    right: 20,
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  examsButton: {
    background: 'linear-gradient(45deg, #4caf50, #2196f3)',
    borderRadius: 8,
    px: 3,
    py: 1.5,
    fontSize: '1.1rem',
    fontWeight: 'bold',
    boxShadow: '0 4px 20px rgba(33, 150, 243, 0.3)',
    '&:hover': {
      background: 'linear-gradient(45deg, #1976d2, #1565c0)',
      boxShadow: '0 6px 25px rgba(33, 150, 243, 0.4)',
      transform: 'translateY(-2px)',
    },
    transition: 'all 0.3s ease',
  },
  addButton: {
    background: 'linear-gradient(45deg, #e91e63, #ff5722)',
    borderRadius: 8,
    px: 3,
    py: 1.5,
    fontSize: '1rem',
    fontWeight: 'bold',
    boxShadow: '0 4px 20px rgba(233, 30, 99, 0.3)',
    '&:hover': {
      background: 'linear-gradient(45deg, #ad1457, #d84315)',
      boxShadow: '0 6px 25px rgba(233, 30, 99, 0.4)',
      transform: 'translateY(-2px)',
    },
    transition: 'all 0.3s ease',
  },
  chatButton: {
    background: 'linear-gradient(45deg, #4caf50, #2196f3)',
    borderRadius: 8,
    px: 3,
    py: 1.5,
    fontSize: '1rem',
    fontWeight: 'bold',
    color: 'white',
    boxShadow: '0 4px 20px rgba(76, 175, 80, 0.3)',
    '&:hover': {
      background: 'linear-gradient(45deg, #388e3c, #1976d2)',
      boxShadow: '0 6px 25px rgba(76, 175, 80, 0.4)',
      transform: 'translateY(-2px)',
    },
    transition: 'all 0.3s ease',
  },
  quizModalBox: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    bgcolor: 'background.paper',
    borderRadius: 4,
    boxShadow: 24,
    p: 4,
    width: '90%',
    maxWidth: 800,
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  chatPaper: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '90%', sm: '450px' },
    height: '600px',
    borderRadius: '12px',
    zIndex: 9999,
    display: 'flex',
    flexDirection: 'column',
  },
  chatHeaderBox: {
    display: 'flex',
    justifyContent: 'flex-end',
    p: 1,
  },
  chatContentBox: {
    flexGrow: 1,
    p: 2,
    overflowY: 'auto',
  },
};
